#update_fastlane
require 'fastlane/actions/scan'
require 'fastlane/actions/snapshot'
default_platform(:ios)

platform :ios do
    MY_XCODE_PROJECT_FILEPATH = File.absolute_path('../Notebowl Mobile.xcodeproj')

    lane :screenshots do
        xcode_select("/Applications/Xcode.app")
        snapshot(
                workspace: File.absolute_path('../Notebowl Mobile.xcworkspace'),
                xcargs: '-only-testing:NotebowlMobileUITests/SnapshotUITests'
        )
        frame_screenshots(white: true)
    end


    lane :manualtests do
        Dir.chdir("../../nb-deployment") do
           sh("./queue-runner-silent.sh")
        end
                    
        xcode_select("/Applications/Xcode.app")
        suppress_tests(
            workspace: File.absolute_path('../Notebowl Mobile.xcworkspace'),
            scheme: 'Notebowl Mobile',
            tests: [
                'NotebowlMobileUITests/CommentUITests',
                'NotebowlMobileUITests/PostUITests',
                'NotebowlMobileUITests/PostDetailViewUITests',
                'NotebowlMobileUITests/SnapshotUITests'
        #        'NotebowlMobileUITests/NotificationUITests'
        #        'NotebowlMobileUITests/MiscAppUITests'
            ]
        )
        scan(
            build_for_testing: true,
            workspace: File.absolute_path('../Notebowl Mobile.xcworkspace'),
            scheme: 'Notebowl Mobile'
        )
        derived_data_path = Scan.config[:derived_data_path]
        xctestrun_file = Dir.glob("#{derived_data_path}/Build/Products/*.xctestrun").first

        tests = tests_from_xctestrun(xctestrun: xctestrun_file)
        UI.header('xctestrun tests')
        tests.values.flatten.each { 
            |test_identifier| puts test_identifier
            run_tests(only_testing: test_identifier)
            Dir.chdir("../../nb-deployment") do 
                sh("./fix-broken-db-nonint.sh")
            end
        }
    end
    
    lane :beta do
        ensure_git_status_clean
        increment_version_number(version_number: "1.7.2", xcodeproj: "Notebowl Mobile.xcodeproj")
        increment_build_number(build_number: "1720000", xcodeproj: "Notebowl Mobile.xcodeproj")
        commit_version_bump(xcodeproj: "Notebowl Mobile.xcodeproj")
        add_git_tag(postfix: "-")
        push_to_git_remote
        xcode_select("/Applications/Xcode 9.app")
        build_app(export_method: "app-store",
                  export_options: {
                    provisioningProfiles: {
                      "com.notebowl.standalone" => "NB Standalone App Store"
                     }
                  },
                  codesigning_identity: "iPhone Distribution: NoteBowl Inc (8M84348K8B)",
                  scheme: "Notebowl Mobile",
                  workspace: "Notebowl Mobile.xcworkspace"
                  )
        upload_to_testflight
        slack(
            channel: "@shotskydiver",
            message: "Successfully uploaded build to App Store Connect",
            slack_url: "https://hooks.slack.com/services/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",
            use_webhook_configured_username_and_icon: "true"
            )                
    end

    lane :refresh_dsyms do
        download_dsyms
        upload_symbols_to_bugsnag
        clean_build_artifacts
    end
end
